# Generated by Django 3.2 on 2022-07-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineasapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='imagen',
            field=models.ImageField(null=True, upload_to='paises'),
        ),
    ]
