# Generated by Django 3.2 on 2022-07-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineasapi', '0002_pais_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(null=True, upload_to='destinos'),
        ),
    ]
