# Generated by Django 3.2 on 2022-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineasapi', '0006_remove_destino_fecha_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
