# Generated by Django 3.2 on 2022-07-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineasapi', '0007_vuelo_fecha_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='cupos_disponibles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='espacios_ocupados',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
