# Generated by Django 4.0.5 on 2022-07-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineasapi', '0009_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='piloto',
        ),
        migrations.RemoveField(
            model_name='vuelopasajero',
            name='pasajero',
        ),
        migrations.RemoveField(
            model_name='vuelopasajero',
            name='vuelo',
        ),
        migrations.DeleteModel(
            name='Avion',
        ),
        migrations.DeleteModel(
            name='Vuelo',
        ),
        migrations.DeleteModel(
            name='VueloPasajero',
        ),
    ]
