# Generated by Django 4.0.5 on 2022-07-24 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aerolineasapi', '0010_remove_vuelo_avion_remove_vuelo_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('fabricante', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('cupos', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('espacios_ocupados', models.SmallIntegerField(blank=True, null=True)),
                ('cupos_disponibles', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolineasapi.avion')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolineasapi.destino')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VueloPasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolineasapi.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolineasapi.vuelo')),
            ],
        ),
    ]
