# Generated by Django 4.0.6 on 2022-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineasapi', '0012_alter_vuelopasajero_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelopasajero',
            name='vuelo',
            field=models.CharField(max_length=150, verbose_name='destino'),
        ),
    ]
