# Generated by Django 4.0.6 on 2022-07-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerolineasapi', '0013_alter_vuelopasajero_vuelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelopasajero',
            old_name='pasajero',
            new_name='user_id',
        ),
    ]
