# Generated by Django 4.0.6 on 2022-07-25 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aerolineasapi', '0014_rename_pasajero_vuelopasajero_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelopasajero',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pasajero',
        ),
    ]
